package com.harry.uac.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.harry.uac.persistence.AuditLog;
import com.harry.uac.persistence.AuditLogExample;

@MyBatisRepository
public interface AuditLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    int countByExample(AuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    int deleteByExample(AuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    int deleteByPrimaryKey(Long auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    int insert(AuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    int insertSelective(AuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    List<AuditLog> selectByExample(AuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    AuditLog selectByPrimaryKey(Long auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    int updateByExampleSelective(@Param("record") AuditLog record, @Param("example") AuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    int updateByExample(@Param("record") AuditLog record, @Param("example") AuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    int updateByPrimaryKeySelective(AuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    int updateByPrimaryKey(AuditLog record);
    
    List<AuditLog> selectPaginationByExample(AuditLogExample example);
}