package com.harry.uac.persistence;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import com.harry.uac.common.util.Page;

public class AuditLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    
    protected Page page;
    
    
    public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	public AuditLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAuditIdIsNull() {
            addCriterion("AUDIT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAuditIdIsNotNull() {
            addCriterion("AUDIT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAuditIdEqualTo(Long value) {
            addCriterion("AUDIT_ID =", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotEqualTo(Long value) {
            addCriterion("AUDIT_ID <>", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdGreaterThan(Long value) {
            addCriterion("AUDIT_ID >", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AUDIT_ID >=", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdLessThan(Long value) {
            addCriterion("AUDIT_ID <", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdLessThanOrEqualTo(Long value) {
            addCriterion("AUDIT_ID <=", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdIn(List<Long> values) {
            addCriterion("AUDIT_ID in", values, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotIn(List<Long> values) {
            addCriterion("AUDIT_ID not in", values, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdBetween(Long value1, Long value2) {
            addCriterion("AUDIT_ID between", value1, value2, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotBetween(Long value1, Long value2) {
            addCriterion("AUDIT_ID not between", value1, value2, "auditId");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNull() {
            addCriterion("OPERATE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNotNull() {
            addCriterion("OPERATE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeEqualTo(Short value) {
            addCriterion("OPERATE_TYPE =", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotEqualTo(Short value) {
            addCriterion("OPERATE_TYPE <>", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThan(Short value) {
            addCriterion("OPERATE_TYPE >", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("OPERATE_TYPE >=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThan(Short value) {
            addCriterion("OPERATE_TYPE <", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThanOrEqualTo(Short value) {
            addCriterion("OPERATE_TYPE <=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIn(List<Short> values) {
            addCriterion("OPERATE_TYPE in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotIn(List<Short> values) {
            addCriterion("OPERATE_TYPE not in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeBetween(Short value1, Short value2) {
            addCriterion("OPERATE_TYPE between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotBetween(Short value1, Short value2) {
            addCriterion("OPERATE_TYPE not between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIsNull() {
            addCriterion("OPERATE_OBJECT is null");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIsNotNull() {
            addCriterion("OPERATE_OBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andOperateObjectEqualTo(Short value) {
            addCriterion("OPERATE_OBJECT =", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectNotEqualTo(Short value) {
            addCriterion("OPERATE_OBJECT <>", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectGreaterThan(Short value) {
            addCriterion("OPERATE_OBJECT >", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectGreaterThanOrEqualTo(Short value) {
            addCriterion("OPERATE_OBJECT >=", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectLessThan(Short value) {
            addCriterion("OPERATE_OBJECT <", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectLessThanOrEqualTo(Short value) {
            addCriterion("OPERATE_OBJECT <=", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIn(List<Short> values) {
            addCriterion("OPERATE_OBJECT in", values, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectNotIn(List<Short> values) {
            addCriterion("OPERATE_OBJECT not in", values, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectBetween(Short value1, Short value2) {
            addCriterion("OPERATE_OBJECT between", value1, value2, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectNotBetween(Short value1, Short value2) {
            addCriterion("OPERATE_OBJECT not between", value1, value2, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateLevelIsNull() {
            addCriterion("OPERATE_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andOperateLevelIsNotNull() {
            addCriterion("OPERATE_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andOperateLevelEqualTo(Short value) {
            addCriterion("OPERATE_LEVEL =", value, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateLevelNotEqualTo(Short value) {
            addCriterion("OPERATE_LEVEL <>", value, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateLevelGreaterThan(Short value) {
            addCriterion("OPERATE_LEVEL >", value, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateLevelGreaterThanOrEqualTo(Short value) {
            addCriterion("OPERATE_LEVEL >=", value, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateLevelLessThan(Short value) {
            addCriterion("OPERATE_LEVEL <", value, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateLevelLessThanOrEqualTo(Short value) {
            addCriterion("OPERATE_LEVEL <=", value, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateLevelIn(List<Short> values) {
            addCriterion("OPERATE_LEVEL in", values, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateLevelNotIn(List<Short> values) {
            addCriterion("OPERATE_LEVEL not in", values, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateLevelBetween(Short value1, Short value2) {
            addCriterion("OPERATE_LEVEL between", value1, value2, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateLevelNotBetween(Short value1, Short value2) {
            addCriterion("OPERATE_LEVEL not between", value1, value2, "operateLevel");
            return (Criteria) this;
        }

        public Criteria andOperateDetailIsNull() {
            addCriterion("OPERATE_DETAIL is null");
            return (Criteria) this;
        }

        public Criteria andOperateDetailIsNotNull() {
            addCriterion("OPERATE_DETAIL is not null");
            return (Criteria) this;
        }

        public Criteria andOperateDetailEqualTo(String value) {
            addCriterion("OPERATE_DETAIL =", value, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailNotEqualTo(String value) {
            addCriterion("OPERATE_DETAIL <>", value, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailGreaterThan(String value) {
            addCriterion("OPERATE_DETAIL >", value, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATE_DETAIL >=", value, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailLessThan(String value) {
            addCriterion("OPERATE_DETAIL <", value, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailLessThanOrEqualTo(String value) {
            addCriterion("OPERATE_DETAIL <=", value, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailLike(String value) {
            addCriterion("OPERATE_DETAIL like", value, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailNotLike(String value) {
            addCriterion("OPERATE_DETAIL not like", value, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailIn(List<String> values) {
            addCriterion("OPERATE_DETAIL in", values, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailNotIn(List<String> values) {
            addCriterion("OPERATE_DETAIL not in", values, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailBetween(String value1, String value2) {
            addCriterion("OPERATE_DETAIL between", value1, value2, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateDetailNotBetween(String value1, String value2) {
            addCriterion("OPERATE_DETAIL not between", value1, value2, "operateDetail");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorIsNull() {
            addCriterion("OPERATE_OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorIsNotNull() {
            addCriterion("OPERATE_OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorEqualTo(Long value) {
            addCriterion("OPERATE_OPERATOR =", value, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorNotEqualTo(Long value) {
            addCriterion("OPERATE_OPERATOR <>", value, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorGreaterThan(Long value) {
            addCriterion("OPERATE_OPERATOR >", value, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("OPERATE_OPERATOR >=", value, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorLessThan(Long value) {
            addCriterion("OPERATE_OPERATOR <", value, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorLessThanOrEqualTo(Long value) {
            addCriterion("OPERATE_OPERATOR <=", value, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorIn(List<Long> values) {
            addCriterion("OPERATE_OPERATOR in", values, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorNotIn(List<Long> values) {
            addCriterion("OPERATE_OPERATOR not in", values, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorBetween(Long value1, Long value2) {
            addCriterion("OPERATE_OPERATOR between", value1, value2, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateOperatorNotBetween(Long value1, Long value2) {
            addCriterion("OPERATE_OPERATOR not between", value1, value2, "operateOperator");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNull() {
            addCriterion("OPERATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNotNull() {
            addCriterion("OPERATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeEqualTo(Date value) {
            addCriterion("OPERATE_TIME =", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotEqualTo(Date value) {
            addCriterion("OPERATE_TIME <>", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThan(Date value) {
            addCriterion("OPERATE_TIME >", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERATE_TIME >=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThan(Date value) {
            addCriterion("OPERATE_TIME <", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("OPERATE_TIME <=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIn(List<Date> values) {
            addCriterion("OPERATE_TIME in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotIn(List<Date> values) {
            addCriterion("OPERATE_TIME not in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeBetween(Date value1, Date value2) {
            addCriterion("OPERATE_TIME between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("OPERATE_TIME not between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 12 15:29:23 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UUM.AUDIT_LOG
     *
     * @mbggenerated Sun Feb 12 15:29:23 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}