package com.harry.uac.persistence;

import java.util.Date;

public class AuditLog {
	
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UUM.AUDIT_LOG.AUDIT_ID
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	private Long auditId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UUM.AUDIT_LOG.OPERATE_TYPE
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	private Short operateType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UUM.AUDIT_LOG.OPERATE_OBJECT
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	private Short operateObject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UUM.AUDIT_LOG.OPERATE_LEVEL
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	private Short operateLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UUM.AUDIT_LOG.OPERATE_DETAIL
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	private String operateDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UUM.AUDIT_LOG.OPERATE_OPERATOR
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	private Long operateOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UUM.AUDIT_LOG.OPERATE_TIME
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	private Date operateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UUM.AUDIT_LOG.CREATE_DATE
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UUM.AUDIT_LOG.UPDATE_DATE
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	private Date updateDate;

	private AuthUser operator;
	

	public AuditLog() {
		
	}

	public AuditLog(Short operateType, Short operateObject, Short operateLevel,
			String operateDetail, Long operateOperator, Date operateTime,
			Date createDate, Date updateDate) {
		this.operateType = operateType;
		this.operateObject = operateObject;
		this.operateLevel = operateLevel;
		this.operateDetail = operateDetail;
		this.operateOperator = operateOperator;
		this.operateTime = operateTime;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UUM.AUDIT_LOG.AUDIT_ID
	 * @return  the value of UUM.AUDIT_LOG.AUDIT_ID
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public Long getAuditId() {
		return auditId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UUM.AUDIT_LOG.AUDIT_ID
	 * @param auditId  the value for UUM.AUDIT_LOG.AUDIT_ID
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public void setAuditId(Long auditId) {
		this.auditId = auditId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UUM.AUDIT_LOG.OPERATE_TYPE
	 * @return  the value of UUM.AUDIT_LOG.OPERATE_TYPE
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public Short getOperateType() {
		return operateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UUM.AUDIT_LOG.OPERATE_TYPE
	 * @param operateType  the value for UUM.AUDIT_LOG.OPERATE_TYPE
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public void setOperateType(Short operateType) {
		this.operateType = operateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UUM.AUDIT_LOG.OPERATE_OBJECT
	 * @return  the value of UUM.AUDIT_LOG.OPERATE_OBJECT
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public Short getOperateObject() {
		return operateObject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UUM.AUDIT_LOG.OPERATE_OBJECT
	 * @param operateObject  the value for UUM.AUDIT_LOG.OPERATE_OBJECT
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public void setOperateObject(Short operateObject) {
		this.operateObject = operateObject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UUM.AUDIT_LOG.OPERATE_LEVEL
	 * @return  the value of UUM.AUDIT_LOG.OPERATE_LEVEL
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public Short getOperateLevel() {
		return operateLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UUM.AUDIT_LOG.OPERATE_LEVEL
	 * @param operateLevel  the value for UUM.AUDIT_LOG.OPERATE_LEVEL
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public void setOperateLevel(Short operateLevel) {
		this.operateLevel = operateLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UUM.AUDIT_LOG.OPERATE_DETAIL
	 * @return  the value of UUM.AUDIT_LOG.OPERATE_DETAIL
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public String getOperateDetail() {
		return operateDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UUM.AUDIT_LOG.OPERATE_DETAIL
	 * @param operateDetail  the value for UUM.AUDIT_LOG.OPERATE_DETAIL
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public void setOperateDetail(String operateDetail) {
		this.operateDetail = operateDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UUM.AUDIT_LOG.OPERATE_OPERATOR
	 * @return  the value of UUM.AUDIT_LOG.OPERATE_OPERATOR
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public Long getOperateOperator() {
		return operateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UUM.AUDIT_LOG.OPERATE_OPERATOR
	 * @param operateOperator  the value for UUM.AUDIT_LOG.OPERATE_OPERATOR
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public void setOperateOperator(Long operateOperator) {
		this.operateOperator = operateOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UUM.AUDIT_LOG.OPERATE_TIME
	 * @return  the value of UUM.AUDIT_LOG.OPERATE_TIME
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public Date getOperateTime() {
		return operateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UUM.AUDIT_LOG.OPERATE_TIME
	 * @param operateTime  the value for UUM.AUDIT_LOG.OPERATE_TIME
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UUM.AUDIT_LOG.CREATE_DATE
	 * @return  the value of UUM.AUDIT_LOG.CREATE_DATE
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UUM.AUDIT_LOG.CREATE_DATE
	 * @param createDate  the value for UUM.AUDIT_LOG.CREATE_DATE
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UUM.AUDIT_LOG.UPDATE_DATE
	 * @return  the value of UUM.AUDIT_LOG.UPDATE_DATE
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UUM.AUDIT_LOG.UPDATE_DATE
	 * @param updateDate  the value for UUM.AUDIT_LOG.UPDATE_DATE
	 * @mbggenerated  Sun Feb 12 15:29:23 CST 2012
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public void setOperator(AuthUser operator) {
		this.operator = operator;
	}

	public AuthUser getOperator() {
		return operator;
	}
}