package com.harry.uac.persistence;

import java.util.Date;

public class SyncIncFieldsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_FIELDS_INFO.ID
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_ID
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    private Long syncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_NAME
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    private String syncFieldsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_PRE_VALUE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    private String syncFieldsPreValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_CUR_VALUE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    private String syncFieldsCurValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_TYPE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    private Short syncFieldsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FILEDS_TABLE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    private String syncFiledsTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_FIELDS_INFO.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_FIELDS_INFO.ID
     *
     * @return the value of UUM.SYNC_INC_FIELDS_INFO.ID
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_FIELDS_INFO.ID
     *
     * @param id the value for UUM.SYNC_INC_FIELDS_INFO.ID
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_ID
     *
     * @return the value of UUM.SYNC_INC_FIELDS_INFO.SYNC_ID
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public Long getSyncId() {
        return syncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_ID
     *
     * @param syncId the value for UUM.SYNC_INC_FIELDS_INFO.SYNC_ID
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setSyncId(Long syncId) {
        this.syncId = syncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_NAME
     *
     * @return the value of UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_NAME
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public String getSyncFieldsName() {
        return syncFieldsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_NAME
     *
     * @param syncFieldsName the value for UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_NAME
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setSyncFieldsName(String syncFieldsName) {
        this.syncFieldsName = syncFieldsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_PRE_VALUE
     *
     * @return the value of UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_PRE_VALUE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public String getSyncFieldsPreValue() {
        return syncFieldsPreValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_PRE_VALUE
     *
     * @param syncFieldsPreValue the value for UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_PRE_VALUE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setSyncFieldsPreValue(String syncFieldsPreValue) {
        this.syncFieldsPreValue = syncFieldsPreValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_CUR_VALUE
     *
     * @return the value of UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_CUR_VALUE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public String getSyncFieldsCurValue() {
        return syncFieldsCurValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_CUR_VALUE
     *
     * @param syncFieldsCurValue the value for UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_CUR_VALUE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setSyncFieldsCurValue(String syncFieldsCurValue) {
        this.syncFieldsCurValue = syncFieldsCurValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_TYPE
     *
     * @return the value of UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_TYPE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public Short getSyncFieldsType() {
        return syncFieldsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_TYPE
     *
     * @param syncFieldsType the value for UUM.SYNC_INC_FIELDS_INFO.SYNC_FIELDS_TYPE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setSyncFieldsType(Short syncFieldsType) {
        this.syncFieldsType = syncFieldsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FILEDS_TABLE
     *
     * @return the value of UUM.SYNC_INC_FIELDS_INFO.SYNC_FILEDS_TABLE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public String getSyncFiledsTable() {
        return syncFiledsTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_FIELDS_INFO.SYNC_FILEDS_TABLE
     *
     * @param syncFiledsTable the value for UUM.SYNC_INC_FIELDS_INFO.SYNC_FILEDS_TABLE
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setSyncFiledsTable(String syncFiledsTable) {
        this.syncFiledsTable = syncFiledsTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_FIELDS_INFO.CREATE_TIME
     *
     * @return the value of UUM.SYNC_INC_FIELDS_INFO.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_FIELDS_INFO.CREATE_TIME
     *
     * @param createTime the value for UUM.SYNC_INC_FIELDS_INFO.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}