package com.harry.uac.persistence;

import java.util.Date;

public class SyncIncInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_INFO.SYNC_ID
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    private Long syncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_INFO.OPERATE_TYPE
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    private Short operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_INFO.OPERATE_OBJECT
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    private String operateObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_INFO.OPERATE_OBJECT_ID
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    private Long operateObjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.SYNC_INC_INFO.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_INFO.SYNC_ID
     *
     * @return the value of UUM.SYNC_INC_INFO.SYNC_ID
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public Long getSyncId() {
        return syncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_INFO.SYNC_ID
     *
     * @param syncId the value for UUM.SYNC_INC_INFO.SYNC_ID
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public void setSyncId(Long syncId) {
        this.syncId = syncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_INFO.OPERATE_TYPE
     *
     * @return the value of UUM.SYNC_INC_INFO.OPERATE_TYPE
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public Short getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_INFO.OPERATE_TYPE
     *
     * @param operateType the value for UUM.SYNC_INC_INFO.OPERATE_TYPE
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public void setOperateType(Short operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_INFO.OPERATE_OBJECT
     *
     * @return the value of UUM.SYNC_INC_INFO.OPERATE_OBJECT
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public String getOperateObject() {
        return operateObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_INFO.OPERATE_OBJECT
     *
     * @param operateObject the value for UUM.SYNC_INC_INFO.OPERATE_OBJECT
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public void setOperateObject(String operateObject) {
        this.operateObject = operateObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_INFO.OPERATE_OBJECT_ID
     *
     * @return the value of UUM.SYNC_INC_INFO.OPERATE_OBJECT_ID
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public Long getOperateObjectId() {
        return operateObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_INFO.OPERATE_OBJECT_ID
     *
     * @param operateObjectId the value for UUM.SYNC_INC_INFO.OPERATE_OBJECT_ID
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public void setOperateObjectId(Long operateObjectId) {
        this.operateObjectId = operateObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_INFO.CREATE_TIME
     *
     * @return the value of UUM.SYNC_INC_INFO.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.SYNC_INC_INFO.CREATE_TIME
     *
     * @param createTime the value for UUM.SYNC_INC_INFO.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}