package com.harry.uac.persistence;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SyncIncInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public SyncIncInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andSyncIdIsNull() {
            addCriterion("SYNC_ID is null");
            return (Criteria) this;
        }

        public Criteria andSyncIdIsNotNull() {
            addCriterion("SYNC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSyncIdEqualTo(Long value) {
            addCriterion("SYNC_ID =", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdNotEqualTo(Long value) {
            addCriterion("SYNC_ID <>", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdGreaterThan(Long value) {
            addCriterion("SYNC_ID >", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SYNC_ID >=", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdLessThan(Long value) {
            addCriterion("SYNC_ID <", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdLessThanOrEqualTo(Long value) {
            addCriterion("SYNC_ID <=", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdIn(List<Long> values) {
            addCriterion("SYNC_ID in", values, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdNotIn(List<Long> values) {
            addCriterion("SYNC_ID not in", values, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdBetween(Long value1, Long value2) {
            addCriterion("SYNC_ID between", value1, value2, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdNotBetween(Long value1, Long value2) {
            addCriterion("SYNC_ID not between", value1, value2, "syncId");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNull() {
            addCriterion("OPERATE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNotNull() {
            addCriterion("OPERATE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeEqualTo(Short value) {
            addCriterion("OPERATE_TYPE =", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotEqualTo(Short value) {
            addCriterion("OPERATE_TYPE <>", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThan(Short value) {
            addCriterion("OPERATE_TYPE >", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("OPERATE_TYPE >=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThan(Short value) {
            addCriterion("OPERATE_TYPE <", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThanOrEqualTo(Short value) {
            addCriterion("OPERATE_TYPE <=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIn(List<Short> values) {
            addCriterion("OPERATE_TYPE in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotIn(List<Short> values) {
            addCriterion("OPERATE_TYPE not in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeBetween(Short value1, Short value2) {
            addCriterion("OPERATE_TYPE between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotBetween(Short value1, Short value2) {
            addCriterion("OPERATE_TYPE not between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIsNull() {
            addCriterion("OPERATE_OBJECT is null");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIsNotNull() {
            addCriterion("OPERATE_OBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andOperateObjectEqualTo(String value) {
            addCriterion("OPERATE_OBJECT =", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectNotEqualTo(String value) {
            addCriterion("OPERATE_OBJECT <>", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectGreaterThan(String value) {
            addCriterion("OPERATE_OBJECT >", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATE_OBJECT >=", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectLessThan(String value) {
            addCriterion("OPERATE_OBJECT <", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectLessThanOrEqualTo(String value) {
            addCriterion("OPERATE_OBJECT <=", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectLike(String value) {
            addCriterion("OPERATE_OBJECT like", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectNotLike(String value) {
            addCriterion("OPERATE_OBJECT not like", value, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIn(List<String> values) {
            addCriterion("OPERATE_OBJECT in", values, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectNotIn(List<String> values) {
            addCriterion("OPERATE_OBJECT not in", values, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectBetween(String value1, String value2) {
            addCriterion("OPERATE_OBJECT between", value1, value2, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectNotBetween(String value1, String value2) {
            addCriterion("OPERATE_OBJECT not between", value1, value2, "operateObject");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdIsNull() {
            addCriterion("OPERATE_OBJECT_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdIsNotNull() {
            addCriterion("OPERATE_OBJECT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdEqualTo(Long value) {
            addCriterion("OPERATE_OBJECT_ID =", value, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdNotEqualTo(Long value) {
            addCriterion("OPERATE_OBJECT_ID <>", value, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdGreaterThan(Long value) {
            addCriterion("OPERATE_OBJECT_ID >", value, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OPERATE_OBJECT_ID >=", value, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdLessThan(Long value) {
            addCriterion("OPERATE_OBJECT_ID <", value, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdLessThanOrEqualTo(Long value) {
            addCriterion("OPERATE_OBJECT_ID <=", value, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdIn(List<Long> values) {
            addCriterion("OPERATE_OBJECT_ID in", values, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdNotIn(List<Long> values) {
            addCriterion("OPERATE_OBJECT_ID not in", values, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdBetween(Long value1, Long value2) {
            addCriterion("OPERATE_OBJECT_ID between", value1, value2, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andOperateObjectIdNotBetween(Long value1, Long value2) {
            addCriterion("OPERATE_OBJECT_ID not between", value1, value2, "operateObjectId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 24 13:48:10 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UUM.SYNC_INC_INFO
     *
     * @mbggenerated Fri Feb 24 13:48:10 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}