package com.harry.uac.persistence;

import java.util.Date;

public class SyncIncStatus {
    private Long id;

    private Long applicationId;

    private Short syncStatus;

    private String syncFailDetails;

    private String syncSuccessDetails;

    private Date createDate;

    private AuthApplication application;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.SYNC_INC_STATUS.ID
     *
     * @return the value of UUM.SYNC_INC_STATUS.ID
     *
     * @mbggenerated Fri Feb 24 13:45:53 CST 2012
     */

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getApplicationId() {
        return applicationId;
    }

    public void setApplicationId(Long applicationId) {
        this.applicationId = applicationId;
    }

    public Short getSyncStatus() {
        return syncStatus;
    }

    public void setSyncStatus(Short syncStatus) {
        this.syncStatus = syncStatus;
    }

    public String getSyncFailDetails() {
        return syncFailDetails;
    }

    public void setSyncFailDetails(String syncFailDetails) {
        this.syncFailDetails = syncFailDetails;
    }

    public String getSyncSuccessDetails() {
        return syncSuccessDetails;
    }

    public void setSyncSuccessDetails(String syncSuccessDetails) {
        this.syncSuccessDetails = syncSuccessDetails;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

	public void setApplication(AuthApplication application) {
		this.application = application;
	}

	public AuthApplication getApplication() {
		return application;
	}

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SyncIncStatus other = (SyncIncStatus) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getApplicationId() == null ? other.getApplicationId() == null : this.getApplicationId().equals(other.getApplicationId()))
            && (this.getSyncStatus() == null ? other.getSyncStatus() == null : this.getSyncStatus().equals(other.getSyncStatus()))
            && (this.getSyncFailDetails() == null ? other.getSyncFailDetails() == null : this.getSyncFailDetails().equals(other.getSyncFailDetails()))
            && (this.getSyncSuccessDetails() == null ? other.getSyncSuccessDetails() == null : this.getSyncSuccessDetails().equals(other.getSyncSuccessDetails()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getApplicationId() == null) ? 0 : getApplicationId().hashCode());
        result = prime * result + ((getSyncStatus() == null) ? 0 : getSyncStatus().hashCode());
        result = prime * result + ((getSyncFailDetails() == null) ? 0 : getSyncFailDetails().hashCode());
        result = prime * result + ((getSyncSuccessDetails() == null) ? 0 : getSyncSuccessDetails().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }

}