package com.harry.uac.persistence;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SyncIncFieldsInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public SyncIncFieldsInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSyncIdIsNull() {
            addCriterion("SYNC_ID is null");
            return (Criteria) this;
        }

        public Criteria andSyncIdIsNotNull() {
            addCriterion("SYNC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSyncIdEqualTo(Long value) {
            addCriterion("SYNC_ID =", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdNotEqualTo(Long value) {
            addCriterion("SYNC_ID <>", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdGreaterThan(Long value) {
            addCriterion("SYNC_ID >", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SYNC_ID >=", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdLessThan(Long value) {
            addCriterion("SYNC_ID <", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdLessThanOrEqualTo(Long value) {
            addCriterion("SYNC_ID <=", value, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdIn(List<Long> values) {
            addCriterion("SYNC_ID in", values, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdNotIn(List<Long> values) {
            addCriterion("SYNC_ID not in", values, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdBetween(Long value1, Long value2) {
            addCriterion("SYNC_ID between", value1, value2, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncIdNotBetween(Long value1, Long value2) {
            addCriterion("SYNC_ID not between", value1, value2, "syncId");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameIsNull() {
            addCriterion("SYNC_FIELDS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameIsNotNull() {
            addCriterion("SYNC_FIELDS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameEqualTo(String value) {
            addCriterion("SYNC_FIELDS_NAME =", value, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameNotEqualTo(String value) {
            addCriterion("SYNC_FIELDS_NAME <>", value, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameGreaterThan(String value) {
            addCriterion("SYNC_FIELDS_NAME >", value, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameGreaterThanOrEqualTo(String value) {
            addCriterion("SYNC_FIELDS_NAME >=", value, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameLessThan(String value) {
            addCriterion("SYNC_FIELDS_NAME <", value, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameLessThanOrEqualTo(String value) {
            addCriterion("SYNC_FIELDS_NAME <=", value, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameLike(String value) {
            addCriterion("SYNC_FIELDS_NAME like", value, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameNotLike(String value) {
            addCriterion("SYNC_FIELDS_NAME not like", value, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameIn(List<String> values) {
            addCriterion("SYNC_FIELDS_NAME in", values, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameNotIn(List<String> values) {
            addCriterion("SYNC_FIELDS_NAME not in", values, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameBetween(String value1, String value2) {
            addCriterion("SYNC_FIELDS_NAME between", value1, value2, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsNameNotBetween(String value1, String value2) {
            addCriterion("SYNC_FIELDS_NAME not between", value1, value2, "syncFieldsName");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueIsNull() {
            addCriterion("SYNC_FIELDS_PRE_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueIsNotNull() {
            addCriterion("SYNC_FIELDS_PRE_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueEqualTo(String value) {
            addCriterion("SYNC_FIELDS_PRE_VALUE =", value, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueNotEqualTo(String value) {
            addCriterion("SYNC_FIELDS_PRE_VALUE <>", value, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueGreaterThan(String value) {
            addCriterion("SYNC_FIELDS_PRE_VALUE >", value, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueGreaterThanOrEqualTo(String value) {
            addCriterion("SYNC_FIELDS_PRE_VALUE >=", value, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueLessThan(String value) {
            addCriterion("SYNC_FIELDS_PRE_VALUE <", value, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueLessThanOrEqualTo(String value) {
            addCriterion("SYNC_FIELDS_PRE_VALUE <=", value, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueLike(String value) {
            addCriterion("SYNC_FIELDS_PRE_VALUE like", value, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueNotLike(String value) {
            addCriterion("SYNC_FIELDS_PRE_VALUE not like", value, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueIn(List<String> values) {
            addCriterion("SYNC_FIELDS_PRE_VALUE in", values, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueNotIn(List<String> values) {
            addCriterion("SYNC_FIELDS_PRE_VALUE not in", values, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueBetween(String value1, String value2) {
            addCriterion("SYNC_FIELDS_PRE_VALUE between", value1, value2, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsPreValueNotBetween(String value1, String value2) {
            addCriterion("SYNC_FIELDS_PRE_VALUE not between", value1, value2, "syncFieldsPreValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueIsNull() {
            addCriterion("SYNC_FIELDS_CUR_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueIsNotNull() {
            addCriterion("SYNC_FIELDS_CUR_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueEqualTo(String value) {
            addCriterion("SYNC_FIELDS_CUR_VALUE =", value, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueNotEqualTo(String value) {
            addCriterion("SYNC_FIELDS_CUR_VALUE <>", value, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueGreaterThan(String value) {
            addCriterion("SYNC_FIELDS_CUR_VALUE >", value, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueGreaterThanOrEqualTo(String value) {
            addCriterion("SYNC_FIELDS_CUR_VALUE >=", value, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueLessThan(String value) {
            addCriterion("SYNC_FIELDS_CUR_VALUE <", value, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueLessThanOrEqualTo(String value) {
            addCriterion("SYNC_FIELDS_CUR_VALUE <=", value, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueLike(String value) {
            addCriterion("SYNC_FIELDS_CUR_VALUE like", value, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueNotLike(String value) {
            addCriterion("SYNC_FIELDS_CUR_VALUE not like", value, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueIn(List<String> values) {
            addCriterion("SYNC_FIELDS_CUR_VALUE in", values, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueNotIn(List<String> values) {
            addCriterion("SYNC_FIELDS_CUR_VALUE not in", values, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueBetween(String value1, String value2) {
            addCriterion("SYNC_FIELDS_CUR_VALUE between", value1, value2, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsCurValueNotBetween(String value1, String value2) {
            addCriterion("SYNC_FIELDS_CUR_VALUE not between", value1, value2, "syncFieldsCurValue");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeIsNull() {
            addCriterion("SYNC_FIELDS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeIsNotNull() {
            addCriterion("SYNC_FIELDS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeEqualTo(Short value) {
            addCriterion("SYNC_FIELDS_TYPE =", value, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeNotEqualTo(Short value) {
            addCriterion("SYNC_FIELDS_TYPE <>", value, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeGreaterThan(Short value) {
            addCriterion("SYNC_FIELDS_TYPE >", value, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("SYNC_FIELDS_TYPE >=", value, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeLessThan(Short value) {
            addCriterion("SYNC_FIELDS_TYPE <", value, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeLessThanOrEqualTo(Short value) {
            addCriterion("SYNC_FIELDS_TYPE <=", value, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeIn(List<Short> values) {
            addCriterion("SYNC_FIELDS_TYPE in", values, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeNotIn(List<Short> values) {
            addCriterion("SYNC_FIELDS_TYPE not in", values, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeBetween(Short value1, Short value2) {
            addCriterion("SYNC_FIELDS_TYPE between", value1, value2, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFieldsTypeNotBetween(Short value1, Short value2) {
            addCriterion("SYNC_FIELDS_TYPE not between", value1, value2, "syncFieldsType");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableIsNull() {
            addCriterion("SYNC_FILEDS_TABLE is null");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableIsNotNull() {
            addCriterion("SYNC_FILEDS_TABLE is not null");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableEqualTo(String value) {
            addCriterion("SYNC_FILEDS_TABLE =", value, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableNotEqualTo(String value) {
            addCriterion("SYNC_FILEDS_TABLE <>", value, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableGreaterThan(String value) {
            addCriterion("SYNC_FILEDS_TABLE >", value, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableGreaterThanOrEqualTo(String value) {
            addCriterion("SYNC_FILEDS_TABLE >=", value, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableLessThan(String value) {
            addCriterion("SYNC_FILEDS_TABLE <", value, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableLessThanOrEqualTo(String value) {
            addCriterion("SYNC_FILEDS_TABLE <=", value, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableLike(String value) {
            addCriterion("SYNC_FILEDS_TABLE like", value, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableNotLike(String value) {
            addCriterion("SYNC_FILEDS_TABLE not like", value, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableIn(List<String> values) {
            addCriterion("SYNC_FILEDS_TABLE in", values, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableNotIn(List<String> values) {
            addCriterion("SYNC_FILEDS_TABLE not in", values, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableBetween(String value1, String value2) {
            addCriterion("SYNC_FILEDS_TABLE between", value1, value2, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andSyncFiledsTableNotBetween(String value1, String value2) {
            addCriterion("SYNC_FILEDS_TABLE not between", value1, value2, "syncFiledsTable");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 24 13:50:42 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UUM.SYNC_INC_FIELDS_INFO
     *
     * @mbggenerated Fri Feb 24 13:50:42 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}