package com.harry.uac.persistence;

public class TempUserAssignKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.TEMP_USER_ASSIGN.ORG_ID
     *
     * @mbggenerated Tue Feb 28 20:33:29 CST 2012
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUM.TEMP_USER_ASSIGN.EMPLOYEE_NUMBER
     *
     * @mbggenerated Tue Feb 28 20:33:29 CST 2012
     */
    private Long employeeNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.TEMP_USER_ASSIGN.ORG_ID
     *
     * @return the value of UUM.TEMP_USER_ASSIGN.ORG_ID
     *
     * @mbggenerated Tue Feb 28 20:33:29 CST 2012
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.TEMP_USER_ASSIGN.ORG_ID
     *
     * @param orgId the value for UUM.TEMP_USER_ASSIGN.ORG_ID
     *
     * @mbggenerated Tue Feb 28 20:33:29 CST 2012
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUM.TEMP_USER_ASSIGN.EMPLOYEE_NUMBER
     *
     * @return the value of UUM.TEMP_USER_ASSIGN.EMPLOYEE_NUMBER
     *
     * @mbggenerated Tue Feb 28 20:33:29 CST 2012
     */
    public Long getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUM.TEMP_USER_ASSIGN.EMPLOYEE_NUMBER
     *
     * @param employeeNumber the value for UUM.TEMP_USER_ASSIGN.EMPLOYEE_NUMBER
     *
     * @mbggenerated Tue Feb 28 20:33:29 CST 2012
     */
    public void setEmployeeNumber(Long employeeNumber) {
        this.employeeNumber = employeeNumber;
    }
}